### ISSUE TITLE
Thunderbird Add-On Link is a 404

### ISSUE THREAD

**Issue by mackenzie-remote** [Amunak/thunderbird-list-unsubscribe-addon#1]
Hello! This add-on looks great, and I'd love to use it, but the link in the GitHub repository to https://addons.thunderbird.net/en-US/thunderbird/addon/list-unsubscribe/ is a 404.

"We're sorry, but we can't find what you're looking for.

The page or file you requested wasn't found on our site. It's possible that you clicked a link that's out of date, or typed in the address incorrectly."

Would love to use it the official way rather than downloading the `.xpi` manually.

Thanks for creating the Add-On too.

**Comment by Roman2K** [comment]
Adding my vote to this request.

It would be nice even if only because this plugin actually works and is nicely put together, especially compared to the only alternative on the Thunderbird add-ons site: ["Unsubscribe"](https://addons.thunderbird.net/en-Us/thunderbird/addon/unsub/).

Also, we would get automatic updates.

**Comment by Amunak** [comment]
Yepp sorry, it got rejected originally for a few minor reasons and I had no time (and later dedication) to get back to it and resubmit it, since it works well for me. I still kinda want to resubmit it, but have very limited time I could dedicate to it recently.

**Comment by sharchun** [comment]
> Would love to use it the official way rather than downloading the `.xpi` manually.

Noob question here, but can somebody please point me to where to download the xpi manually??  I don't see any such file in the repo and don't have the tools/knowhow to package it myself.  Thanks!

**Comment by Amunak** [comment]
> please point me to where to download the xpi manually?


You can download it in the [release](https://github.com/Amunak/thunderbird-list-unsubscribe-addon/releases/tag/1.0.0): [list_unsubscribe-1.0.0-tb.xpi ](https://github.com/Amunak/thunderbird-list-unsubscribe-addon/releases/download/1.0.0/list_unsubscribe-1.0.0-tb.xpi)

**Comment by jobisoft** [comment]
Hi, I filed a PR (https://github.com/Amunak/thunderbird-list-unsubscribe-addon/pull/2) to address the issues reported during the initial review.

The submission was rejected because it had a spelling error (= bug) and we wanted to prevent this awesome add-on from getting bad reviews on the initial submission. We did not intend to prevent this add-on from being listed in general.

There is a second issue, which is more technical (a so-called policy violation), because the original submission is requesting the `webRequest` permission, which we do not see being used.
